---

- name: "01.1 - set cluster variable combining ip list and ports"
  set_fact:
    # we need to get a string value, like:
    #   "master-0=http://10.0.0.1:2380,master-1=http://10.0.0.2:2380"
    _etcd_initial_cluster: "{{ _etcd_initial_cluster|default('') + item.0 + '=https://' + item.1 + ':' + __etcd_listen_peer_port|string + (ansible_loop.last | ternary('', ',')) }}"
  loop: "{{ etcd_initial_cluster_member_names.split(',')|zip(etcd_initial_cluster_member_ips.split(','))|list }}"
  loop_control:
    extended: yes

- name: "01.2 - make sure base play directory exists and world writable"
  file:
    path: "{{ __etcd_play_dir }}"
    state: directory
    owner: 0
    group: 0
    mode: "a=rwX"
  become: yes

- name: "01.3.1 - add system group for etcd"
  group:
    name: "{{ __etcd_group }}"
    state: present
    system: yes
  become: yes

- name: "01.3.2 - add system user for etcd"
  user:
    name: "{{ __etcd_user }}"
    system: yes
    group: "{{ __etcd_group }}"
    home: "{{ __etcd_data_dir }}"
    shell: /usr/sbin/nologin
    state: present
    force: yes
    remove: yes
  become: yes

- name: "01.4 - make sure etcd config and data directories exist"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ __etcd_user }}"
    group: "{{ __etcd_group }}"
    mode: "ug=rwX,o-rwx"
  become: yes
  loop:
    - "{{ __etcd_config_dir }}"
    - "{{ __etcd_pki_dir }}"
    - "{{ __etcd_data_dir }}"
