---

- name: "02.1 - download etcd archive"
  get_url:
    url: "{{ __etcd_download_url }}"
    dest: "{{ __etcd_play_dir }}/etcd-${etcd_version}.tar.gz"
  register: _etcd_archive_download

- name: "02.2.1 - make sure directory for etcd unpacked files is created"
  file:
    path: "{{ __etcd_play_dir }}/etcd-{{ etcd_version }}"
    state: directory

- name: "02.2.2 - unpack etcd archive"
  shell:
    cmd: "tar -xzf {{ __etcd_play_dir }}/etcd-{{ etcd_version }}.tar.gz -C {{ __etcd_play_dir }}/etcd-{{ etcd_version }} --strip-components=1"
  args:
    warn: no
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: yes
  changed_when: no

- name: "02.3 - install etcd binaries"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    owner: "{{ __etcd_user }}"
    group: "{{ __etcd_group }}"
    mode: "0755"
  become: yes
  loop:
    - src: "{{ __etcd_play_dir }}/etcd-{{ etcd_version }}/etcd"
      dest: "{{ __etcd_binary }}"
    - src: "{{ __etcd_play_dir }}/etcd-{{ etcd_version }}/etcdctl"
      dest: "{{ __etcd_client_binary }}"
