---

- name: "03.1 - place all the pki data into appropriate place"
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    owner: "{{ __etcd_user }}"
    group: "{{ __etcd_group }}"
    mode: "ug=rwX,o-rwx"
  become: yes
  loop_control:
    label: "{{ item.dest }}"
  loop:
    - content: "{{ etcd_ca_cert }}"
      dest: "{{ __etcd_pki_ca_cert_file }}"
    - content: "{{ etcd_server_cert }}"
      dest: "{{ __etcd_pki_server_cert_file }}"
    - content: "{{ etcd_server_key }}"
      dest: "{{ __etcd_pki_server_key_file }}"
    - content: "{{ etcd_peer_cert }}"
      dest: "{{ __etcd_pki_peer_cert_file }}"
    - content: "{{ etcd_peer_key }}"
      dest: "{{ __etcd_pki_peer_key_file }}"
  notify:
    - etcd-restart-service

- name: "03.2 - template etcd systemd unit"
  template:
    src: etcd.service
    dest: "{{ __etcd_service_systemd_unit }}"
  become: yes
  notify:
    - etcd-reload-systemd
    - etcd-restart-service

- meta: flush_handlers