---

- include_tasks: 01-prepare-env.yml

- include_tasks: 02-install-packages.yml

- include_tasks: 03-configure-etcd.yml

- name: "0.4 - make sure etcd service is started"
  service:
    name: "{{ __etcd_service }}"
    state: started
    enabled: yes
  become: yes
